# Limpieza de datos

In [533]:
import pandas as pd

path = "/Users/juandavidescobarescobar/Documents/Unir/Materias/BD Big Data/Actividad 3/visa01_grupal 2/act-grupal-openDataLocalesMadrid.xlsx"

df = pd.read_excel(path)

print(df.shape) 

(2999, 36)


In [534]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   _id                     2999 non-null   int64  
 1   id_local                2999 non-null   int64  
 2   id_distrito_local       2999 non-null   int64  
 3   desc_distrito_local     2999 non-null   object 
 4   desc_barrio_local       2999 non-null   object 
 5   clase_vial_edificio     2999 non-null   object 
 6   num_edificio            2999 non-null   int64  
 7   Cod_Postal              2999 non-null   int64  
 8   coordenada_x_local      2999 non-null   float64
 9   coordenada_y_local      2999 non-null   float64
 10  desc_situacion_local    2999 non-null   object 
 11  Nombre                  2999 non-null   object 
 12  id_periodo_terraza      2999 non-null   int64  
 13  desc_periodo_terraza    2999 non-null   object 
 14  id_situacion_terraza    2999 non-null   

In [535]:
df.tail(5)

_id   id_local  id_distrito_local   desc_distrito_local  \
2994  4640  270469031                 10  LATINA                 
2995  4641  200000726                 20  SAN BLAS-CANILLEJAS    
2996  4642  270432183                 20  SAN BLAS-CANILLEJAS    
2997  4643  110002324                 11  CARABANCHEL            
2998  4647  270474279                  7  CHAMBERI               

         desc_barrio_local       clase_vial_edificio  num_edificio  \
2994  ALUCHE                CALLE                                7   
2995  ROSAS                 AVENIDA                            131   
2996  ROSAS                 AVENIDA                             67   
2997  VISTA ALEGRE          CALLE                                2   
2998  RIOS ROSAS            CALLE                               60   

      Cod_Postal  coordenada_x_local  coordenada_y_local  ... hora_ini_VS_es  \
2994       28024           435079.62          4471833.57  ...       10:00:00   
2995       28022           448206.56          4475309.42  ...       10:00:00   
2996       28022           448410.56          4476163.42  ...       08:00:00   
2997       28025           437303.60          4471032.54  ...       10:00:00   
2998       28003           440863.60          4477144.53  ...       08:00:00   

     hora_fin_VS_es  hora_ini_VS_ra hora_fin_VS_ra  mesas_aux_es mesas_aux_ra  \
2994       02:30:00        10:00:00       00:00:00             0          0.0   
2995       02:00:00             NaN            NaN             0          NaN   
2996       01:30:00        08:00:00       01:00:00             0          0.0   
2997       01:30:00             NaN            NaN             0          NaN   
2998       01:30:00        08:00:00       01:00:00             0          0.0   

      mesas_es mesas_ra sillas_es  sillas_ra  
2994         6      6.0        12             
2995         6      NaN        15             
2996        16      8.0        64          A  
2997        12      NaN        24             
2998         2      2.0         4             

[5 rows x 36 columns]

In [536]:
df.describe()

_id      id_local  id_distrito_local  num_edificio  \
count  2999.000000  2.999000e+03        2999.000000   2999.000000   
mean   2317.493498  2.319233e+08           8.024341     40.743248   
std    1347.996658  8.456402e+07           6.016966     61.608959   
min       7.000000  1.000000e+07           1.000000      1.000000   
25%    1163.500000  2.700438e+08           2.000000      7.000000   
50%    2306.000000  2.703250e+08           7.000000     19.000000   
75%    3557.500000  2.705515e+08          13.000000     49.000000   
max    4647.000000  2.900008e+08          21.000000    638.000000   

         Cod_Postal  coordenada_x_local  coordenada_y_local  \
count   2999.000000         2999.000000        2.999000e+03   
mean   28021.063021       437565.771061        4.431328e+06   
std       14.679056        43340.420824        4.379662e+05   
min    28001.000000            0.000000        0.000000e+00   
25%    28009.000000       439953.095000        4.472605e+06   
50%    28017.000000       441022.580000        4.474585e+06   
75%    28031.000000       443329.580000        4.476366e+06   
max    28054.000000       452050.560000        4.487142e+06   

       id_periodo_terraza  id_situacion_terraza  Superficie_ES  num_terraza  \
count         2999.000000           2999.000000    2999.000000  2999.000000   
mean             1.296099              1.032678      33.042474    41.522174   
std              0.456611              0.477233      39.777599    64.082279   
min              1.000000              1.000000       0.970000     1.000000   
25%              1.000000              1.000000      13.905000     7.000000   
50%              1.000000              1.000000      24.930000    20.000000   
75%              2.000000              1.000000      41.685000    50.000000   
max              2.000000              8.000000     920.000000   638.000000   

       mesas_aux_es  mesas_aux_ra     mesas_es     mesas_ra    sillas_es  
count   2999.000000   2151.000000  2999.000000  2151.000000  2999.000000  
mean       0.041681      0.044630    10.226075     9.794514    34.224075  
std        0.243522      0.251244     6.839890     7.180114    24.371181  
min        0.000000      0.000000     0.000000     0.000000     0.000000  
25%        0.000000      0.000000     6.000000     5.000000    17.000000  
50%        0.000000      0.000000     8.000000     8.000000    28.000000  
75%        0.000000      0.000000    13.000000    13.000000    45.000000  
max        4.000000      2.000000    57.000000   112.000000   184.000000

In [537]:
idx = df.applymap(lambda x: isinstance(x, str)).all(0)
df_str = df[df.columns[idx]]

list_cols_sts = df_str.columns.to_list()
print(list_cols_sts)

['desc_distrito_local', 'desc_barrio_local', 'clase_vial_edificio', 'desc_situacion_local', 'Nombre', 'desc_periodo_terraza', 'desc_situacion_terraza', 'DESC_CLASE', 'DESC_NOMBRE', 'cal_terraza', 'desc_ubicacion_terraza']


In [538]:
"""
Eliminar espacios en blanco a la derecha e izquierda de las columnas tipo object (string)
"""

# for col in list_cols_sts:
#     print(col)
#     df[col] = str(df[col]).strip()

df[df_str.columns] = df_str.apply(lambda x: x.str.strip())

In [539]:
# """
# Eliminar columnas (__1	__2	__3	__4	__5	__6	__7) generadas dinamicamente por
# valores errados, hallados en el registro _id = 2812.
# """

# df.drop(['__1', '__2', '__3','__4','__5','__6','__7'], axis=1, inplace=True)

In [540]:
df.tail(5)

_id   id_local  id_distrito_local  desc_distrito_local  \
2994  4640  270469031                 10               LATINA   
2995  4641  200000726                 20  SAN BLAS-CANILLEJAS   
2996  4642  270432183                 20  SAN BLAS-CANILLEJAS   
2997  4643  110002324                 11          CARABANCHEL   
2998  4647  270474279                  7             CHAMBERI   

     desc_barrio_local clase_vial_edificio  num_edificio  Cod_Postal  \
2994            ALUCHE               CALLE             7       28024   
2995             ROSAS             AVENIDA           131       28022   
2996             ROSAS             AVENIDA            67       28022   
2997      VISTA ALEGRE               CALLE             2       28025   
2998        RIOS ROSAS               CALLE            60       28003   

      coordenada_x_local  coordenada_y_local  ... hora_ini_VS_es  \
2994           435079.62          4471833.57  ...       10:00:00   
2995           448206.56          4475309.42  ...       10:00:00   
2996           448410.56          4476163.42  ...       08:00:00   
2997           437303.60          4471032.54  ...       10:00:00   
2998           440863.60          4477144.53  ...       08:00:00   

     hora_fin_VS_es  hora_ini_VS_ra hora_fin_VS_ra  mesas_aux_es mesas_aux_ra  \
2994       02:30:00        10:00:00       00:00:00             0          0.0   
2995       02:00:00             NaN            NaN             0          NaN   
2996       01:30:00        08:00:00       01:00:00             0          0.0   
2997       01:30:00             NaN            NaN             0          NaN   
2998       01:30:00        08:00:00       01:00:00             0          0.0   

      mesas_es mesas_ra sillas_es  sillas_ra  
2994         6      6.0        12             
2995         6      NaN        15             
2996        16      8.0        64          A  
2997        12      NaN        24             
2998         2      2.0         4             

[5 rows x 36 columns]

In [541]:
cols = df.columns.to_list()

for col in cols:
    #df[col] = df_obj.apply(lambda x: x.str.strip())
    print(col, ":", df[col].unique)

_id : <bound method Series.unique of 0          7
1         32
2         33
3         34
4         36
        ... 
2994    4640
2995    4641
2996    4642
2997    4643
2998    4647
Name: _id, Length: 2999, dtype: int64>
id_local : <bound method Series.unique of 0       280067128
1       270068967
2       270403150
3       270078567
4        40002021
          ...    
2994    270469031
2995    200000726
2996    270432183
2997    110002324
2998    270474279
Name: id_local, Length: 2999, dtype: int64>
id_distrito_local : <bound method Series.unique of 0       20
1        4
2        4
3        4
4        4
        ..
2994    10
2995    20
2996    20
2997    11
2998     7
Name: id_distrito_local, Length: 2999, dtype: int64>
desc_distrito_local : <bound method Series.unique of 0       SAN BLAS-CANILLEJAS
1                 SALAMANCA
2                 SALAMANCA
3                 SALAMANCA
4                 SALAMANCA
               ...         
2994                 LATINA
2995    SAN BLAS-CANILL

Name: sillas_es, Length: 2999, dtype: int64>
sillas_ra : <bound method Series.unique of 0        A
1         
2         
3         
4         
        ..
2994      
2995      
2996     A
2997      
2998      
Name: sillas_ra, Length: 2999, dtype: object>


In [542]:
len(df["desc_distrito_local"][1])

9

In [543]:
df['hora_ini_VS_es'].unique()

array([datetime.time(8, 0), datetime.time(10, 0), datetime.time(13, 0),
       datetime.time(2, 30), datetime.time(8, 30), datetime.time(12, 0),
       datetime.time(9, 0), datetime.time(1, 30), datetime.time(0, 0),
       datetime.time(10, 24), datetime.time(11, 0)], dtype=object)

In [544]:
df['hora_fin_VS_es'].unique()

array([datetime.time(1, 30), datetime.time(2, 30), datetime.time(0, 0),
       datetime.time(1, 0), datetime.time(0, 30), datetime.time(2, 0),
       datetime.time(22, 0), datetime.time(23, 0), datetime.time(21, 0),
       datetime.time(23, 30), datetime.time(12, 0), datetime.time(8, 30),
       datetime.time(20, 30)], dtype=object)

In [545]:
df['hora_ini_VS_ra'].unique()

array([nan, datetime.time(10, 0), datetime.time(8, 0),
       datetime.time(9, 0), datetime.time(21, 0), datetime.time(2, 30),
       datetime.time(0, 0), datetime.time(11, 0), datetime.time(18, 0)],
      dtype=object)

In [546]:
df['hora_fin_VS_ra'].unique()

array([nan, datetime.time(0, 0), datetime.time(1, 0),
       datetime.time(23, 59), datetime.time(23, 0), datetime.time(0, 30),
       datetime.time(22, 0), datetime.time(2, 0), datetime.time(12, 0),
       datetime.time(23, 20), datetime.time(1, 30), datetime.time(2, 30),
       datetime.time(23, 30)], dtype=object)

In [547]:
"""
Replazar Null Values para las columnas:

-hora_ini_VS_es
-hora_fin_VS_es
-hora_ini_VS_ra
-hora_fin_VS_ra
"""

import numpy as np

df['hora_ini_VS_es'] = df['hora_ini_VS_es'].replace(np.nan, "")
df['hora_fin_VS_es'] = df['hora_fin_VS_es'].replace(np.nan, "")

df['hora_ini_VS_ra'] = df['hora_ini_VS_ra'].replace(np.nan, "")
df['hora_fin_VS_ra'] = df['hora_fin_VS_ra'].replace(np.nan, "")

In [548]:
df = df.astype({"hora_ini_VS_es": str}, errors='raise') 
df = df.astype({"hora_fin_VS_es": str}, errors='raise') 
df = df.astype({"hora_ini_VS_ra": str}, errors='raise') 
df = df.astype({"hora_fin_VS_ra": str}, errors='raise')       

df.dtypes

_id                         int64
id_local                    int64
id_distrito_local           int64
desc_distrito_local        object
desc_barrio_local          object
clase_vial_edificio        object
num_edificio                int64
Cod_Postal                  int64
coordenada_x_local        float64
coordenada_y_local        float64
desc_situacion_local       object
Nombre                     object
id_periodo_terraza          int64
desc_periodo_terraza       object
id_situacion_terraza        int64
desc_situacion_terraza     object
Superficie_ES             float64
DESC_CLASE                 object
DESC_NOMBRE                object
num_terraza                 int64
cal_terraza                object
desc_ubicacion_terraza     object
hora_ini_LJ_es             object
hora_fin_LJ_es             object
hora_ini_LJ_ra             object
hora_fin_LJ_ra             object
hora_ini_VS_es             object
hora_fin_VS_es             object
hora_ini_VS_ra             object
hora_fin_VS_ra

In [549]:
df['hora_ini_VS_es'].unique()

array(['08:00:00', '10:00:00', '13:00:00', '02:30:00', '08:30:00',
       '12:00:00', '09:00:00', '01:30:00', '00:00:00', '10:24:00',
       '11:00:00'], dtype=object)

In [550]:
df['hora_fin_VS_es'].unique()

array(['01:30:00', '02:30:00', '00:00:00', '01:00:00', '00:30:00',
       '02:00:00', '22:00:00', '23:00:00', '21:00:00', '23:30:00',
       '12:00:00', '08:30:00', '20:30:00'], dtype=object)

In [551]:
df['hora_ini_VS_ra'].unique()

array(['', '10:00:00', '08:00:00', '09:00:00', '21:00:00', '02:30:00',
       '00:00:00', '11:00:00', '18:00:00'], dtype=object)

In [552]:
df['hora_fin_VS_ra'].unique()

array(['', '00:00:00', '01:00:00', '23:59:00', '23:00:00', '00:30:00',
       '22:00:00', '02:00:00', '12:00:00', '23:20:00', '01:30:00',
       '02:30:00', '23:30:00'], dtype=object)

In [553]:
"""
Replazar Null Values para las columnas:

-mesas_aux_es
-mesas_aux_ra
-mesas_es
-mesas_ra
"""
import numpy as np

df['mesas_es'] = df['mesas_es'].fillna(0).replace(np.nan, 0).replace("" , 0)
df['mesas_aux_es'] = df['mesas_aux_es'].fillna(0).replace(np.nan, 0).replace("" , 0)

df['mesas_ra'] = df['mesas_ra'].fillna(0).replace(np.nan, 0).replace("" , 0)
df['mesas_aux_ra'] = df['mesas_aux_ra'].fillna(0).replace(np.nan, 0).replace("" , 0)

In [554]:
df['mesas_ra'].unique()

array([  0.,   9.,   8.,   6.,  21.,   3.,  10.,  12.,  30.,  16.,  15.,
        22.,  11.,   7.,  24.,  18.,  17.,   4.,  20.,  14.,   5.,  29.,
        26.,  28.,   2.,  13.,  25.,  19.,  23.,  27.,  38.,  57.,  37.,
        34.,  33.,   1.,  32.,  40.,  76.,  39.,  41.,  44.,  42., 112.])

In [555]:
df['mesas_aux_ra'].unique()

array([0., 1., 2.])

In [556]:
df = df.astype({"mesas_aux_es": int}, errors='raise') 
df = df.astype({"mesas_aux_ra": int}, errors='raise') 
df = df.astype({"mesas_es": int}, errors='raise') 
df = df.astype({"mesas_ra": int}, errors='raise')       

df.dtypes

_id                         int64
id_local                    int64
id_distrito_local           int64
desc_distrito_local        object
desc_barrio_local          object
clase_vial_edificio        object
num_edificio                int64
Cod_Postal                  int64
coordenada_x_local        float64
coordenada_y_local        float64
desc_situacion_local       object
Nombre                     object
id_periodo_terraza          int64
desc_periodo_terraza       object
id_situacion_terraza        int64
desc_situacion_terraza     object
Superficie_ES             float64
DESC_CLASE                 object
DESC_NOMBRE                object
num_terraza                 int64
cal_terraza                object
desc_ubicacion_terraza     object
hora_ini_LJ_es             object
hora_fin_LJ_es             object
hora_ini_LJ_ra             object
hora_fin_LJ_ra             object
hora_ini_VS_es             object
hora_fin_VS_es             object
hora_ini_VS_ra             object
hora_fin_VS_ra

In [557]:
# Remplazar valores nulos y vacios en columnas tipo entero

# df_col_int = df.select_dtypes('int64')

# cols = df.df_col_int.to_list()

# for col in cols:
#     df[col] = df[col].fillna(0)

In [558]:
df.columns

Index(['_id', 'id_local', 'id_distrito_local', 'desc_distrito_local',
       'desc_barrio_local', 'clase_vial_edificio', 'num_edificio',
       'Cod_Postal', 'coordenada_x_local', 'coordenada_y_local',
       'desc_situacion_local', 'Nombre', 'id_periodo_terraza',
       'desc_periodo_terraza', 'id_situacion_terraza',
       'desc_situacion_terraza', 'Superficie_ES', 'DESC_CLASE', 'DESC_NOMBRE',
       'num_terraza', 'cal_terraza', 'desc_ubicacion_terraza',
       'hora_ini_LJ_es', 'hora_fin_LJ_es', 'hora_ini_LJ_ra', 'hora_fin_LJ_ra',
       'hora_ini_VS_es', 'hora_fin_VS_es', 'hora_ini_VS_ra', 'hora_fin_VS_ra',
       'mesas_aux_es', 'mesas_aux_ra', 'mesas_es', 'mesas_ra', 'sillas_es',
       'sillas_ra'],
      dtype='object')

In [559]:
df.tail(5)

_id   id_local  id_distrito_local  desc_distrito_local  \
2994  4640  270469031                 10               LATINA   
2995  4641  200000726                 20  SAN BLAS-CANILLEJAS   
2996  4642  270432183                 20  SAN BLAS-CANILLEJAS   
2997  4643  110002324                 11          CARABANCHEL   
2998  4647  270474279                  7             CHAMBERI   

     desc_barrio_local clase_vial_edificio  num_edificio  Cod_Postal  \
2994            ALUCHE               CALLE             7       28024   
2995             ROSAS             AVENIDA           131       28022   
2996             ROSAS             AVENIDA            67       28022   
2997      VISTA ALEGRE               CALLE             2       28025   
2998        RIOS ROSAS               CALLE            60       28003   

      coordenada_x_local  coordenada_y_local  ... hora_ini_VS_es  \
2994           435079.62          4471833.57  ...       10:00:00   
2995           448206.56          4475309.42  ...       10:00:00   
2996           448410.56          4476163.42  ...       08:00:00   
2997           437303.60          4471032.54  ...       10:00:00   
2998           440863.60          4477144.53  ...       08:00:00   

     hora_fin_VS_es  hora_ini_VS_ra hora_fin_VS_ra  mesas_aux_es mesas_aux_ra  \
2994       02:30:00        10:00:00       00:00:00             0            0   
2995       02:00:00                                            0            0   
2996       01:30:00        08:00:00       01:00:00             0            0   
2997       01:30:00                                            0            0   
2998       01:30:00        08:00:00       01:00:00             0            0   

      mesas_es mesas_ra sillas_es  sillas_ra  
2994         6        6        12             
2995         6        0        15             
2996        16        8        64          A  
2997        12        0        24             
2998         2        2         4             

[5 rows x 36 columns]

In [560]:
# Validar valores de la variable 'sillas_ra'
df['sillas_es'].unique()

array([ 10,  20,  27,  14,  24,  92,  35,   9,  16,  32,  12,  47,  13,
        36, 120, 112,  80,  44,  40,  56,  60,  18,  64,  88,  42,  28,
        96,  72,  68,  84,  30,  63,  61,  26,  21,  25,  48,  97,  31,
        76,  54, 152,  34,  38, 104, 107,   6,  43,  52,  11, 108, 100,
         4,  57,  23,  53,  33,  98,  66,  29,  15,  74,   8,  70,  99,
       105,  22,  50,  51, 124,  19,  45,  59,  17,  58,  69,  82, 136,
        46, 149, 116,  65,  90,   7,   0, 102, 115,  37, 156, 114, 110,
        39, 128, 113,  78,  55,  85,  94,   2,  71,  62, 125,  79,  67,
         5,  93,  81,  41,  86,  49, 118,  87, 160, 109,  77, 150,   3,
        75, 101,  95, 121, 106,  91,  73, 184, 117])

In [561]:
# Validar valores de la variable 'sillas_ra'
df['sillas_ra'].unique()

array([' A', '  ', ' B', ' C', ' D', ' E', ' G', ' F', ' H',
       datetime.datetime(1900, 1, 1, 3, 13, 20), ' L'], dtype=object)

In [562]:
# Replazar Null Values para las columnas:

df['sillas_ra'] = df['sillas_ra'].fillna(0).replace(np.nan, 0).replace("" , 0)
df = df.astype({"mesas_ra": int}, errors='raise')  

In [563]:
# Replazando valores vacios y atipicos de la variable número de sillas 'sillas_ra'

df['sillas_ra'] = 0
df['sillas_ra'].unique()

array([0])

In [564]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   _id                     2999 non-null   int64  
 1   id_local                2999 non-null   int64  
 2   id_distrito_local       2999 non-null   int64  
 3   desc_distrito_local     2999 non-null   object 
 4   desc_barrio_local       2999 non-null   object 
 5   clase_vial_edificio     2999 non-null   object 
 6   num_edificio            2999 non-null   int64  
 7   Cod_Postal              2999 non-null   int64  
 8   coordenada_x_local      2999 non-null   float64
 9   coordenada_y_local      2999 non-null   float64
 10  desc_situacion_local    2999 non-null   object 
 11  Nombre                  2999 non-null   object 
 12  id_periodo_terraza      2999 non-null   int64  
 13  desc_periodo_terraza    2999 non-null   object 
 14  id_situacion_terraza    2999 non-null   

In [565]:
df['mesas_es'].unique()

array([ 5, 10,  9,  4,  8,  6, 27, 14,  3, 12, 30, 21, 11, 16, 15, 22,  7,
       24, 18, 17, 25, 20, 38, 26, 28,  2, 13, 19, 23, 31, 29, 34, 57, 36,
        0, 37, 56, 55, 33,  1, 32, 35, 40, 39, 44, 46, 42])

In [566]:
df['mesas_aux_es'].unique()

array([0, 1, 2, 4])

In [567]:
df['mesas_ra'].unique()

array([  0,   9,   8,   6,  21,   3,  10,  12,  30,  16,  15,  22,  11,
         7,  24,  18,  17,   4,  20,  14,   5,  29,  26,  28,   2,  13,
        25,  19,  23,  27,  38,  57,  37,  34,  33,   1,  32,  40,  76,
        39,  41,  44,  42, 112])

In [568]:
df['mesas_aux_ra'].unique()

array([0, 1, 2])

In [569]:
print(df.shape) 

(2999, 36)


In [570]:
df.tail(5)

_id   id_local  id_distrito_local  desc_distrito_local  \
2994  4640  270469031                 10               LATINA   
2995  4641  200000726                 20  SAN BLAS-CANILLEJAS   
2996  4642  270432183                 20  SAN BLAS-CANILLEJAS   
2997  4643  110002324                 11          CARABANCHEL   
2998  4647  270474279                  7             CHAMBERI   

     desc_barrio_local clase_vial_edificio  num_edificio  Cod_Postal  \
2994            ALUCHE               CALLE             7       28024   
2995             ROSAS             AVENIDA           131       28022   
2996             ROSAS             AVENIDA            67       28022   
2997      VISTA ALEGRE               CALLE             2       28025   
2998        RIOS ROSAS               CALLE            60       28003   

      coordenada_x_local  coordenada_y_local  ... hora_ini_VS_es  \
2994           435079.62          4471833.57  ...       10:00:00   
2995           448206.56          4475309.42  ...       10:00:00   
2996           448410.56          4476163.42  ...       08:00:00   
2997           437303.60          4471032.54  ...       10:00:00   
2998           440863.60          4477144.53  ...       08:00:00   

     hora_fin_VS_es  hora_ini_VS_ra hora_fin_VS_ra  mesas_aux_es mesas_aux_ra  \
2994       02:30:00        10:00:00       00:00:00             0            0   
2995       02:00:00                                            0            0   
2996       01:30:00        08:00:00       01:00:00             0            0   
2997       01:30:00                                            0            0   
2998       01:30:00        08:00:00       01:00:00             0            0   

      mesas_es mesas_ra sillas_es  sillas_ra  
2994         6        6        12          0  
2995         6        0        15          0  
2996        16        8        64          0  
2997        12        0        24          0  
2998         2        2         4          0  

[5 rows x 36 columns]

In [571]:
# path = '/Users/juandavidescobarescobar/Documents/Unir/Materias/BD Big Data/Actividad 3/visa01_grupal/'
# file = 'act-grupal-openDataLocalesMadrid-[corregido4].csv'

# df.to_csv(path + file, index=0)

# Modelo de datos NEO4J

## Tablas

### Tabla (Nodo) - Terraza

In [572]:
path = '/Users/juandavidescobarescobar/Library/Application Support/Neo4j Desktop/Application/relate-data/dbmss/dbms-d0c5cb43-2ea0-4f88-8d25-c17b87b0018e/import/DS_Neo4j/'

In [573]:
df.rename(columns={'_id': 'id_terraza'}, inplace=True)

In [574]:
df.sort_values('id_terraza')
df.tail(3)

id_terraza   id_local  id_distrito_local  desc_distrito_local  \
2996        4642  270432183                 20  SAN BLAS-CANILLEJAS   
2997        4643  110002324                 11          CARABANCHEL   
2998        4647  270474279                  7             CHAMBERI   

     desc_barrio_local clase_vial_edificio  num_edificio  Cod_Postal  \
2996             ROSAS             AVENIDA            67       28022   
2997      VISTA ALEGRE               CALLE             2       28025   
2998        RIOS ROSAS               CALLE            60       28003   

      coordenada_x_local  coordenada_y_local  ... hora_ini_VS_es  \
2996           448410.56          4476163.42  ...       08:00:00   
2997           437303.60          4471032.54  ...       10:00:00   
2998           440863.60          4477144.53  ...       08:00:00   

     hora_fin_VS_es  hora_ini_VS_ra hora_fin_VS_ra  mesas_aux_es mesas_aux_ra  \
2996       01:30:00        08:00:00       01:00:00             0            0   
2997       01:30:00                                            0            0   
2998       01:30:00        08:00:00       01:00:00             0            0   

      mesas_es mesas_ra sillas_es  sillas_ra  
2996        16        8        64          0  
2997        12        0        24          0  
2998         2        2         4          0  

[3 rows x 36 columns]

In [575]:
df = df.loc[1:100]

In [576]:
df_Terraza =  df[["id_terraza",
                  "Superficie_ES",
                  "hora_ini_LJ_es",
                  "hora_fin_LJ_es",
                  "hora_ini_LJ_ra",
                  "hora_fin_LJ_ra",
                  "hora_ini_VS_es",
                  "hora_fin_VS_es",
                  "hora_ini_VS_ra",
                  "hora_fin_VS_ra",
                  "mesas_aux_es",
                  "mesas_aux_ra",
                  "mesas_es",
                  "mesas_ra",
                  "sillas_es",
                  "sillas_ra",
                  "DESC_CLASE",
                  "DESC_NOMBRE",
                  "num_terraza",
                  "cal_terraza",
                  "desc_ubicacion_terraza"]]

df_Terraza.tail(3)

id_terraza  Superficie_ES hora_ini_LJ_es hora_fin_LJ_es hora_ini_LJ_ra  \
98          175          44.64       10:00:00       01:00:00       10:00:00   
99          177          94.07       10:00:00       01:00:00       10:00:00   
100         179          90.72       08:00:00       01:30:00       08:00:00   

    hora_fin_LJ_ra hora_ini_VS_es hora_fin_VS_es hora_ini_VS_ra  \
98        00:00:00       10:00:00       02:30:00       10:00:00   
99        00:00:00       10:00:00       02:30:00       10:00:00   
100       01:00:00       08:00:00       01:30:00       08:00:00   

    hora_fin_VS_ra  ...  mesas_aux_ra  mesas_es  mesas_ra  sillas_es  \
98        00:00:00  ...             0        14        14         38   
99        00:00:00  ...             0        26        26        104   
100       01:00:00  ...             0        28        28        107   

     sillas_ra  DESC_CLASE                        DESC_NOMBRE num_terraza  \
98           0       CALLE                        FERROCARRIL          19   
99           0       PLAZA                     GENERAL MAROTO           1   
100          0       PASEO  JUAN ANTONIO VALLEJO-NAJERA BOTAS          18   

     cal_terraza desc_ubicacion_terraza  
98                                Acera  
99                                Acera  
100                             Bulevar  

[3 rows x 21 columns]

In [577]:
df_Terraza.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 1 to 100
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   id_terraza              100 non-null    int64  
 1   Superficie_ES           100 non-null    float64
 2   hora_ini_LJ_es          100 non-null    object 
 3   hora_fin_LJ_es          100 non-null    object 
 4   hora_ini_LJ_ra          76 non-null     object 
 5   hora_fin_LJ_ra          76 non-null     object 
 6   hora_ini_VS_es          100 non-null    object 
 7   hora_fin_VS_es          100 non-null    object 
 8   hora_ini_VS_ra          100 non-null    object 
 9   hora_fin_VS_ra          100 non-null    object 
 10  mesas_aux_es            100 non-null    int64  
 11  mesas_aux_ra            100 non-null    int64  
 12  mesas_es                100 non-null    int64  
 13  mesas_ra                100 non-null    int64  
 14  sillas_es               100 non-null    in

In [578]:


file = 'terrazas.csv'
df_Terraza.to_csv(path + file, index=0)

### Tabla (Nodo) - Local

In [579]:
df_Local =  df[["id_local",
                "desc_situacion_local",
                "Nombre",
                "clase_vial_edificio",
                "num_edificio",
                "Cod_Postal",
                "coordenada_x_local",
                "coordenada_y_local"
               ]]

df_Local.tail(3)

id_local desc_situacion_local                    Nombre  \
98   270057250              Abierto     CAFETERIA FERROCARRIL   
99   280017278              Abierto  RESTARAURANTE  O'PORTI?O   
100  280018318              Abierto             LA MARGHERITA   

    clase_vial_edificio  num_edificio  Cod_Postal  coordenada_x_local  \
98                CALLE            19       28045           440931.58   
99                PLAZA             1       28045           440739.58   
100               CALLE            33       28005           440313.59   

     coordenada_y_local  
98           4472464.52  
99           4471734.52  
100          4472551.53

In [580]:


file = 'locales.csv'
df_Local.to_csv(path + file, index=0)

### Tabla (Nodo) - Periodo_Estacional

In [581]:
df_Periodo_Estacional =  df[["id_periodo_terraza",
                              "desc_periodo_terraza"                              
                         ]]
df_Periodo_Estacional.tail(3)

id_periodo_terraza desc_periodo_terraza
98                    1                Anual
99                    1                Anual
100                   1                Anual

In [582]:


file = 'periodo_estacional.csv'
df_Periodo_Estacional.to_csv(path + file, index=0)

### Tabla (Nodo) - Situacion_Terraza

In [583]:
df_Situacion_Terraza =  df[["id_situacion_terraza",
                            "desc_situacion_terraza"          
                         ]]

df_Situacion_Terraza.tail(3)

id_situacion_terraza desc_situacion_terraza
98                      1                Abierta
99                      1                Abierta
100                     1                Abierta

In [584]:


file = 'situacion_terraza.csv'
df_Situacion_Terraza.to_csv(path + file, index=0)

### Tabla (Nodo) - Municipio

In [585]:
df_Municipio =  df[["id_distrito_local",
                    "desc_distrito_local"]]
df_Municipio.tail(3)

id_distrito_local desc_distrito_local
98                   2          ARGANZUELA
99                   2          ARGANZUELA
100                  2          ARGANZUELA

In [586]:


file = 'municipios.csv'
df_Municipio.to_csv(path + file, index=0)

### Tabla (Nodo) - Barrio

In [587]:
df_Barrios =  df[["desc_barrio_local"]]
df_Barrios.tail(3)

desc_barrio_local
98           DELICIAS
99            CHOPERA
100           ACACIAS

In [588]:


file = 'barrios.csv'
df_Barrios.to_csv(path + file, index=0)

## Tablas tipo Relacion

### Tabla (Nodo) - Rel Terraza - Local

In [589]:
df_Contiene =  df[["id_terraza",
                    "id_local"]]
df_Contiene.tail(3)

id_terraza   id_local
98          175  270057250
99          177  280017278
100         179  280018318

In [590]:


file = 'rel_contiene.csv'
df_Contiene.to_csv(path + file, index=0)

### Tabla (Nodo) - Rel Local - Municipio

In [591]:
df_Pertenece =  df[["id_local",
                    "id_distrito_local"]]
df_Pertenece.tail(3)

id_local  id_distrito_local
98   270057250                  2
99   280017278                  2
100  280018318                  2

In [592]:


file = 'rel_pertenece.csv'
df_Pertenece.to_csv(path + file, index=0)

### Tabla (Nodo) - Rel Municipio - Barrio

In [593]:
import numpy as np


df_EsContenedor= df[["id_distrito_local", "desc_barrio_local"]] 

df_EsContenedor = df_EsContenedor.drop_duplicates(['id_distrito_local','desc_barrio_local'])[['id_distrito_local','desc_barrio_local']]

df_EsContenedor.tail(20)

id_distrito_local     desc_barrio_local
17                 20              SIMANCAS
18                 20                 REJAS
19                 17            SAN ANDRES
21                 21                 TIMON
22                 18  ENSANCHE DE VALLECAS
24                 17              BUTARQUE
28                 17           LOS ANGELES
36                 18         SANTA EUGENIA
60                  2               CHOPERA
61                  2       PALOS DE MOGUER
62                  2              IMPERIAL
67                 12              MOSCARDO
70                 12            PRADOLONGO
72                 12           ALMENDRALES
73                 12            SAN FERMIN
74                  2               ACACIAS
79                  9             ARGUELLES
85                 12               ORCASUR
86                 12             ORCASITAS
98                  2              DELICIAS

In [594]:
df_EsContenedor.tail(3)

id_distrito_local desc_barrio_local
85                 12           ORCASUR
86                 12         ORCASITAS
98                  2          DELICIAS

In [595]:


file = 'rel_es_contenedor.csv'
df_EsContenedor.to_csv(path + file, index=0)

### Tabla (Nodo) - Rel Terraza - Periodo_Estacional

In [596]:
df_Esta =  df[["id_terraza",
               "id_periodo_terraza"]]
df_Esta.tail(3)

id_terraza  id_periodo_terraza
98          175                   1
99          177                   1
100         179                   1

In [597]:


file = 'rel_esta.csv'
df_Esta.to_csv(path + file, index=0)

### Tabla (Nodo) - Rel Terraza - Situacion_Terraza

In [598]:
df_TieneSituacion =  df[["id_terraza",
                         "id_situacion_terraza"]]
df_TieneSituacion.tail(3)

id_terraza  id_situacion_terraza
98          175                     1
99          177                     1
100         179                     1

In [599]:

file = 'rel_tiene_situacion.csv'
df_TieneSituacion.to_csv(path + file, index=0)